<?php

?>
<div>
    <div class="group-form block-center">
        <div class="group-btn">
            <a class="btn btn-primary" href="/site/add-user">Добавить пользователя</a>
            <a class="btn btn-primary" href="/site/add-role">Добавить роль</a>
        </div>
    </div>
    <div class="group-form">

        <?php if (isset($user)): ?>
            <?php if (is_array($user) && count($user) !== 0): ?>
                <h2 class="text-center">Список Пользователей</h2>
                <div class="table">
                    <div class="tr header">
                        <span class="col-3">#</span>
                        <span class="col-3">Пользователь</span>
                        <span class="col-3">Роль</span>
                    </div>
                    <?php foreach ($user as $key => $value): ?>
                        <div class="tr">
                            <span class="col-3"><?= ($key + 1); ?></span>
                            <span class="col-3"><?= $value['user_name']; ?></span>
                            <span class="col-3"><?= $value['role_name']; ?></span>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php else: ?>
                <div class="alert alert-warning">
                    В таблицу Пользователей нет записей
                </div>

            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
